const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log(" ZK-ORIGIN Contract Deployment");
    
    const [deployer] = await ethers.getSigners();
    console.log("Deploying with account:", deployer.address);
    console.log("Network:", network.name);
    
    const balance = await ethers.provider.getBalance(deployer.address);
    console.log("Balance:", ethers.formatEther(balance), "ETH\n");
    
    // Check if we have the real Groth16Verifier
    let groth16VerifierAddress;
    
    try {
        // Try to deploy the real verifier (generated by snarkjs)
        console.log(" Deploying Groth16Verifier...");
        const Groth16Verifier = await ethers.getContractFactory("Groth16Verifier");
        const groth16Verifier = await Groth16Verifier.deploy();
        await groth16Verifier.waitForDeployment();
        groth16VerifierAddress = await groth16Verifier.getAddress();
        console.log("   Groth16Verifier deployed to:", groth16VerifierAddress);
    } catch (error) {
        // Fall back to mock verifier
        console.log("  Real Groth16Verifier not found, deploying mock...");
        const MockVerifier = await ethers.getContractFactory("MockGroth16Verifier");
        const mockVerifier = await MockVerifier.deploy();
        await mockVerifier.waitForDeployment();
        groth16VerifierAddress = await mockVerifier.getAddress();
        console.log("   MockGroth16Verifier deployed to:", groth16VerifierAddress);
    }
    
    // Deploy LineageVerifier
    console.log("\n Deploying LineageVerifier...");
    const LineageVerifier = await ethers.getContractFactory("LineageVerifier");
    const lineageVerifier = await LineageVerifier.deploy(groth16VerifierAddress);
    await lineageVerifier.waitForDeployment();
    const lineageVerifierAddress = await lineageVerifier.getAddress();
    console.log("   LineageVerifier deployed to:", lineageVerifierAddress);
    
    // Deploy PolicyRegistry
    console.log("\n Deploying PolicyRegistry...");
    const PolicyRegistry = await ethers.getContractFactory("PolicyRegistry");
    const policyRegistry = await PolicyRegistry.deploy();
    await policyRegistry.waitForDeployment();
    const policyRegistryAddress = await policyRegistry.getAddress();
    console.log("   PolicyRegistry deployed to:", policyRegistryAddress);
    
    // Save deployment info
    const deploymentInfo = {
        network: network.name,
        deployer: deployer.address,
        timestamp: new Date().toISOString(),
        contracts: {
            Groth16Verifier: groth16VerifierAddress,
            LineageVerifier: lineageVerifierAddress,
            PolicyRegistry: policyRegistryAddress
        }
    };
    
    const deploymentsDir = path.join(__dirname, "../deployments", network.name);
    if (!fs.existsSync(deploymentsDir)) {
        fs.mkdirSync(deploymentsDir, { recursive: true });
    }
    
    fs.writeFileSync(
        path.join(deploymentsDir, "addresses.json"),
        JSON.stringify(deploymentInfo, null, 2)
    );
    
    console.log("\n Deployment complete!");
    console.log("\n Deployment info saved to:", path.join(deploymentsDir, "addresses.json"));
    
    console.log("\nContract Addresses:");
    console.log("   Groth16Verifier:", groth16VerifierAddress);
    console.log("   LineageVerifier:", lineageVerifierAddress);
    console.log("   PolicyRegistry:", policyRegistryAddress);
    
    if (network.name === "sepolia") {
        console.log("\nVerify on Etherscan:");
        console.log(`   npx hardhat verify --network sepolia ${lineageVerifierAddress} ${groth16VerifierAddress}`);
    }
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });